[mgr]
show_hidden = true
# parent:current:preview. The default is [1, 4, 3]
ratio = [1, 2, 5]

[opener]
edit = [
  { run = '$HOME/bin/code-with-root %s', desc = "code (git root)", orphan = true, for = "unix" },
]
